# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('room_numb', models.CharField(max_length=10, verbose_name='房间号')),
                ('identity', models.IntegerField(default=1, verbose_name='身份属性')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
    ]
