# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='电子邮箱'),
        ),
    ]
