# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('d01', models.IntegerField(default=0, verbose_name='灯泡')),
                ('d02', models.IntegerField(default=0, verbose_name='可调亮度灯泡')),
                ('d03', models.IntegerField(default=0, verbose_name='风扇')),
                ('d04', models.IntegerField(default=0, verbose_name='窗帘')),
                ('d05', models.IntegerField(default=0, verbose_name='门锁')),
                ('d06', models.IntegerField(default=0, verbose_name='舵机')),
                ('d07', models.IntegerField(default=1, verbose_name='摄像')),
                ('d08', models.IntegerField(default=1, verbose_name='温湿度传感器')),
                ('d09', models.IntegerField(default=1, verbose_name='光照传感器')),
                ('d10', models.IntegerField(default=1, verbose_name='CO2传感器')),
                ('d11', models.IntegerField(default=1, verbose_name='PM2.5传感器')),
                ('d12', models.IntegerField(default=1, verbose_name='紫外传感器')),
                ('d13', models.IntegerField(default=1, verbose_name='烟雾传感器')),
                ('d14', models.IntegerField(default=1, verbose_name='火光传感器')),
                ('d15', models.IntegerField(default=1, verbose_name='红外传感器')),
            ],
            options={
                'verbose_name_plural': '设备状态',
                'verbose_name': '设备状态',
            },
        ),
    ]
