# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital', '0005_device_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_bedheight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='病床高度选择')),
            ],
            options={
                'verbose_name': '可调高度病床',
                'verbose_name_plural': '可调高度病床',
            },
        ),
        migrations.CreateModel(
            name='Table_CO2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='CO2浓度')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': 'CO2传感器',
                'verbose_name_plural': 'CO2传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='颜色选择')),
            ],
            options={
                'verbose_name': '可调颜色灯泡',
                'verbose_name_plural': '可调颜色灯泡',
            },
        ),
        migrations.CreateModel(
            name='Table_guangzhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='光强')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '光照传感器',
                'verbose_name_plural': '光照传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_hongwai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('test', models.IntegerField(verbose_name='有无人感应')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '红外传感器',
                'verbose_name_plural': '红外传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_huoguang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('test', models.IntegerField(verbose_name='有无火光')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '火光传感器',
                'verbose_name_plural': '火光传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_jiawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='浓度')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '甲烷传感器',
                'verbose_name_plural': '甲烷传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_liangdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='亮度选择')),
            ],
            options={
                'verbose_name': '可调亮度灯泡',
                'verbose_name_plural': '可调亮度灯泡',
            },
        ),
        migrations.CreateModel(
            name='Table_PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='PM2.5浓度')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': 'PM2.5传感器',
                'verbose_name_plural': 'PM2.5传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_tishi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('option', models.CharField(max_length=30, verbose_name='操作种类')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '烟雾传感器',
                'verbose_name_plural': '烟雾传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_wsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data1', models.CharField(max_length=20, verbose_name='温度')),
                ('data12', models.CharField(max_length=20, verbose_name='湿度')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '温湿度传感器',
                'verbose_name_plural': '温湿度传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_yanwu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('test', models.IntegerField(verbose_name='有无烟雾')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '烟雾传感器',
                'verbose_name_plural': '烟雾传感器',
            },
        ),
        migrations.CreateModel(
            name='Table_ziwaixian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号码')),
                ('data', models.CharField(max_length=20, verbose_name='紫外线强度')),
                ('cur_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '紫外线传感器',
                'verbose_name_plural': '紫外线传感器',
            },
        ),
        migrations.AddField(
            model_name='device_state',
            name='d16',
            field=models.IntegerField(default=1, null=True, verbose_name='火光传感器'),
        ),
        migrations.AddField(
            model_name='device_state',
            name='d17',
            field=models.IntegerField(default=1, null=True, verbose_name='红外传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d01',
            field=models.IntegerField(default=0, verbose_name='风扇'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d02',
            field=models.IntegerField(default=0, verbose_name='窗帘'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d03',
            field=models.IntegerField(default=0, verbose_name='自动门锁'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d04',
            field=models.IntegerField(default=0, verbose_name='可调颜色灯泡'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d05',
            field=models.IntegerField(default=0, verbose_name='可调亮度灯泡'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d06',
            field=models.IntegerField(default=0, verbose_name='病床（舵机）'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d07',
            field=models.IntegerField(default=1, verbose_name='报警灯（LED灯）'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d08',
            field=models.IntegerField(default=1, verbose_name='报警器（喇叭）'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d09',
            field=models.IntegerField(default=1, verbose_name='甲烷传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d10',
            field=models.IntegerField(default=1, verbose_name='温湿度传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d11',
            field=models.IntegerField(default=1, verbose_name='光照传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d12',
            field=models.IntegerField(default=1, verbose_name='CO2传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d13',
            field=models.IntegerField(default=1, verbose_name='PM2.5传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d14',
            field=models.IntegerField(default=1, verbose_name='紫外线传感器'),
        ),
        migrations.AlterField(
            model_name='device_state',
            name='d15',
            field=models.IntegerField(default=1, verbose_name='烟雾传感器'),
        ),
    ]
