# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehospital', '0006_auto_20180719_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table_tishi',
            options={'verbose_name': '提示', 'verbose_name_plural': '提示'},
        ),
    ]
